[package]
cairo-version = "2.2.0"
name = "zknight"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">=2.2.0"
alexandria_data_structures = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "46c8d8ab9e3bfb68b70a29b3246f809cd8bf70e4" }
dojo = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.1" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
# world_address = "0x5797dca16591ca89ac11a7946e962185dfad886f029d91bb57339eeb94c57fa"

# Madara testnet
# rpc_url = "https://api.cartridge.gg/x/shinai/madara"
# account_address = "0x2"
# private_key = "0xc1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d"
